// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feature.proto

package openconfig_profiles

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// method_name specifies the name of the method that is
// being tested. The methods are from the gnmi service (e.g., Get).
type GNMIService_Method int32

const (
	GNMIService_MD_INVALID      GNMIService_Method = 0
	GNMIService_MD_GET          GNMIService_Method = 1
	GNMIService_MD_CAPABILITIES GNMIService_Method = 2
	GNMIService_MD_SUBSCRIBE    GNMIService_Method = 3
	GNMIService_MD_SET          GNMIService_Method = 4
)

var GNMIService_Method_name = map[int32]string{
	0: "MD_INVALID",
	1: "MD_GET",
	2: "MD_CAPABILITIES",
	3: "MD_SUBSCRIBE",
	4: "MD_SET",
}

var GNMIService_Method_value = map[string]int32{
	"MD_INVALID":      0,
	"MD_GET":          1,
	"MD_CAPABILITIES": 2,
	"MD_SUBSCRIBE":    3,
	"MD_SET":          4,
}

func (x GNMIService_Method) Enum() *GNMIService_Method {
	p := new(GNMIService_Method)
	*p = x
	return p
}

func (x GNMIService_Method) String() string {
	return proto.EnumName(GNMIService_Method_name, int32(x))
}

func (x *GNMIService_Method) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GNMIService_Method_value, data, "GNMIService_Method")
	if err != nil {
		return err
	}
	*x = GNMIService_Method(value)
	return nil
}

func (GNMIService_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3af9f7912a9c0618, []int{4, 0}
}

type FeatureProfileID struct {
	// Unique name for the feature profile.
	//
	// Example: bgp_base
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Version number for this instantiation of the profile.
	Version              *int32   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureProfileID) Reset()         { *m = FeatureProfileID{} }
func (m *FeatureProfileID) String() string { return proto.CompactTextString(m) }
func (*FeatureProfileID) ProtoMessage()    {}
func (*FeatureProfileID) Descriptor() ([]byte, []int) {
	return fileDescriptor_3af9f7912a9c0618, []int{0}
}

func (m *FeatureProfileID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureProfileID.Unmarshal(m, b)
}
func (m *FeatureProfileID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureProfileID.Marshal(b, m, deterministic)
}
func (m *FeatureProfileID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureProfileID.Merge(m, src)
}
func (m *FeatureProfileID) XXX_Size() int {
	return xxx_messageInfo_FeatureProfileID.Size(m)
}
func (m *FeatureProfileID) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureProfileID.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureProfileID proto.InternalMessageInfo

func (m *FeatureProfileID) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *FeatureProfileID) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type TelemetryPath struct {
	Path                 *string  `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelemetryPath) Reset()         { *m = TelemetryPath{} }
func (m *TelemetryPath) String() string { return proto.CompactTextString(m) }
func (*TelemetryPath) ProtoMessage()    {}
func (*TelemetryPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_3af9f7912a9c0618, []int{1}
}

func (m *TelemetryPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelemetryPath.Unmarshal(m, b)
}
func (m *TelemetryPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelemetryPath.Marshal(b, m, deterministic)
}
func (m *TelemetryPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelemetryPath.Merge(m, src)
}
func (m *TelemetryPath) XXX_Size() int {
	return xxx_messageInfo_TelemetryPath.Size(m)
}
func (m *TelemetryPath) XXX_DiscardUnknown() {
	xxx_messageInfo_TelemetryPath.DiscardUnknown(m)
}

var xxx_messageInfo_TelemetryPath proto.InternalMessageInfo

func (m *TelemetryPath) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

type ConfigPath struct {
	Path                 *string  `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigPath) Reset()         { *m = ConfigPath{} }
func (m *ConfigPath) String() string { return proto.CompactTextString(m) }
func (*ConfigPath) ProtoMessage()    {}
func (*ConfigPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_3af9f7912a9c0618, []int{2}
}

func (m *ConfigPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigPath.Unmarshal(m, b)
}
func (m *ConfigPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigPath.Marshal(b, m, deterministic)
}
func (m *ConfigPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigPath.Merge(m, src)
}
func (m *ConfigPath) XXX_Size() int {
	return xxx_messageInfo_ConfigPath.Size(m)
}
func (m *ConfigPath) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigPath.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigPath proto.InternalMessageInfo

func (m *ConfigPath) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

type GNOIService struct {
	// Service name for the GNOI endpoint
	//
	// Example: gnoi.bgp.BGP
	ServiceName *string `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	// Method name for GNOI endpoint
	//
	// Example: ClearBGPNeighbor
	MethodName           *string  `protobuf:"bytes,2,opt,name=method_name,json=methodName" json:"method_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GNOIService) Reset()         { *m = GNOIService{} }
func (m *GNOIService) String() string { return proto.CompactTextString(m) }
func (*GNOIService) ProtoMessage()    {}
func (*GNOIService) Descriptor() ([]byte, []int) {
	return fileDescriptor_3af9f7912a9c0618, []int{3}
}

func (m *GNOIService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GNOIService.Unmarshal(m, b)
}
func (m *GNOIService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GNOIService.Marshal(b, m, deterministic)
}
func (m *GNOIService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GNOIService.Merge(m, src)
}
func (m *GNOIService) XXX_Size() int {
	return xxx_messageInfo_GNOIService.Size(m)
}
func (m *GNOIService) XXX_DiscardUnknown() {
	xxx_messageInfo_GNOIService.DiscardUnknown(m)
}

var xxx_messageInfo_GNOIService proto.InternalMessageInfo

func (m *GNOIService) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *GNOIService) GetMethodName() string {
	if m != nil && m.MethodName != nil {
		return *m.MethodName
	}
	return ""
}

// GNMIService describes compliance with the gNMI service.
type GNMIService struct {
	// The method that is covered within the gNMI protocol.
	MethodName           *GNMIService_Method `protobuf:"varint,2,opt,name=method_name,json=methodName,enum=openconfig.profiles.GNMIService_Method" json:"method_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GNMIService) Reset()         { *m = GNMIService{} }
func (m *GNMIService) String() string { return proto.CompactTextString(m) }
func (*GNMIService) ProtoMessage()    {}
func (*GNMIService) Descriptor() ([]byte, []int) {
	return fileDescriptor_3af9f7912a9c0618, []int{4}
}

func (m *GNMIService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GNMIService.Unmarshal(m, b)
}
func (m *GNMIService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GNMIService.Marshal(b, m, deterministic)
}
func (m *GNMIService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GNMIService.Merge(m, src)
}
func (m *GNMIService) XXX_Size() int {
	return xxx_messageInfo_GNMIService.Size(m)
}
func (m *GNMIService) XXX_DiscardUnknown() {
	xxx_messageInfo_GNMIService.DiscardUnknown(m)
}

var xxx_messageInfo_GNMIService proto.InternalMessageInfo

func (m *GNMIService) GetMethodName() GNMIService_Method {
	if m != nil && m.MethodName != nil {
		return *m.MethodName
	}
	return GNMIService_MD_INVALID
}

type FeatureProfile struct {
	// Unique identifier for the service profile.
	Id *FeatureProfileID `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// A list of configuration and state paths that compose the feature profile.
	ConfigPath []*ConfigPath `protobuf:"bytes,2,rep,name=config_path,json=configPath" json:"config_path,omitempty"`
	// A list of configuration and state paths that compose the feature profile.
	TelemetryPath []*TelemetryPath `protobuf:"bytes,3,rep,name=telemetry_path,json=telemetryPath" json:"telemetry_path,omitempty"`
	// A list of feature profiles this feature profile depends on.  For example,
	// A iBGP feature profile might depend on the BGP base feature profile.
	FeatureProfileDependency []*FeatureProfileID `protobuf:"bytes,4,rep,name=feature_profile_dependency,json=featureProfileDependency" json:"feature_profile_dependency,omitempty"`
	// A list of GNOI operational commands that compose the feature profile.
	GnoiService []*GNOIService `protobuf:"bytes,5,rep,name=gnoi_service,json=gnoiService" json:"gnoi_service,omitempty"`
	// A list of GNMI methods that compose the feature profile.
	GnmiService          []*GNMIService `protobuf:"bytes,6,rep,name=gnmi_service,json=gnmiService" json:"gnmi_service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FeatureProfile) Reset()         { *m = FeatureProfile{} }
func (m *FeatureProfile) String() string { return proto.CompactTextString(m) }
func (*FeatureProfile) ProtoMessage()    {}
func (*FeatureProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_3af9f7912a9c0618, []int{5}
}

func (m *FeatureProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureProfile.Unmarshal(m, b)
}
func (m *FeatureProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureProfile.Marshal(b, m, deterministic)
}
func (m *FeatureProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureProfile.Merge(m, src)
}
func (m *FeatureProfile) XXX_Size() int {
	return xxx_messageInfo_FeatureProfile.Size(m)
}
func (m *FeatureProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureProfile.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureProfile proto.InternalMessageInfo

func (m *FeatureProfile) GetId() *FeatureProfileID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *FeatureProfile) GetConfigPath() []*ConfigPath {
	if m != nil {
		return m.ConfigPath
	}
	return nil
}

func (m *FeatureProfile) GetTelemetryPath() []*TelemetryPath {
	if m != nil {
		return m.TelemetryPath
	}
	return nil
}

func (m *FeatureProfile) GetFeatureProfileDependency() []*FeatureProfileID {
	if m != nil {
		return m.FeatureProfileDependency
	}
	return nil
}

func (m *FeatureProfile) GetGnoiService() []*GNOIService {
	if m != nil {
		return m.GnoiService
	}
	return nil
}

func (m *FeatureProfile) GetGnmiService() []*GNMIService {
	if m != nil {
		return m.GnmiService
	}
	return nil
}

func init() {
	proto.RegisterEnum("openconfig.profiles.GNMIService_Method", GNMIService_Method_name, GNMIService_Method_value)
	proto.RegisterType((*FeatureProfileID)(nil), "openconfig.profiles.FeatureProfileID")
	proto.RegisterType((*TelemetryPath)(nil), "openconfig.profiles.TelemetryPath")
	proto.RegisterType((*ConfigPath)(nil), "openconfig.profiles.ConfigPath")
	proto.RegisterType((*GNOIService)(nil), "openconfig.profiles.GNOIService")
	proto.RegisterType((*GNMIService)(nil), "openconfig.profiles.GNMIService")
	proto.RegisterType((*FeatureProfile)(nil), "openconfig.profiles.FeatureProfile")
}

func init() {
	proto.RegisterFile("feature.proto", fileDescriptor_3af9f7912a9c0618)
}

var fileDescriptor_3af9f7912a9c0618 = []byte{
	// 425 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x8f, 0x93, 0x40,
	0x18, 0xc6, 0x05, 0xba, 0x35, 0xbe, 0xb4, 0x48, 0x66, 0x2f, 0xc4, 0xcb, 0x22, 0xc6, 0xd8, 0x13,
	0x87, 0x26, 0xde, 0xb7, 0x05, 0x5c, 0x27, 0x59, 0x6a, 0x05, 0xd4, 0xe3, 0x84, 0xc0, 0xb0, 0x25,
	0x59, 0xfe, 0x84, 0x8e, 0x9b, 0xf4, 0x5b, 0xf9, 0x1d, 0xfc, 0x62, 0x86, 0x19, 0x68, 0x8b, 0x52,
	0xb3, 0xb7, 0xe1, 0xcd, 0xf3, 0xfc, 0x78, 0x67, 0x9e, 0x07, 0xe6, 0x19, 0x8d, 0xd9, 0xcf, 0x86,
	0xda, 0x75, 0x53, 0xb1, 0x0a, 0x5d, 0x57, 0x35, 0x2d, 0x93, 0xaa, 0xcc, 0xf2, 0x87, 0x76, 0x92,
	0xe5, 0x8f, 0x74, 0x6f, 0xdd, 0x82, 0xfe, 0x49, 0xa8, 0xb6, 0x62, 0x84, 0x5d, 0x84, 0x60, 0x52,
	0xc6, 0x05, 0x35, 0x24, 0x53, 0x5a, 0xbc, 0x0a, 0xf8, 0x19, 0x19, 0xf0, 0xf2, 0x89, 0x36, 0xfb,
	0xbc, 0x2a, 0x0d, 0xd9, 0x94, 0x16, 0x57, 0x41, 0xff, 0x69, 0xbd, 0x83, 0x79, 0x44, 0x1f, 0x69,
	0x41, 0x59, 0x73, 0xd8, 0xc6, 0x6c, 0xd7, 0xda, 0xeb, 0x98, 0xed, 0x7a, 0x7b, 0x7b, 0xb6, 0x4c,
	0x00, 0x87, 0xff, 0xf9, 0xa2, 0xe2, 0x2b, 0xa8, 0x77, 0x9b, 0x2f, 0x38, 0xa4, 0xcd, 0x53, 0x9e,
	0x50, 0xf4, 0x16, 0x66, 0x7b, 0x71, 0x24, 0x67, 0xbb, 0xa8, 0xdd, 0x6c, 0xd3, 0xae, 0x74, 0x03,
	0x6a, 0x41, 0xd9, 0xae, 0x4a, 0x85, 0x42, 0xe6, 0x0a, 0x10, 0xa3, 0x56, 0x60, 0xfd, 0x92, 0x5a,
	0xa6, 0x7f, 0x64, 0x7e, 0xfe, 0xd7, 0xa0, 0x2d, 0x3f, 0xd8, 0x23, 0xcf, 0x62, 0x9f, 0xd9, 0x6c,
	0x9f, 0x7b, 0x06, 0xe4, 0x1f, 0x30, 0x15, 0x53, 0xa4, 0x01, 0xf8, 0x2e, 0xc1, 0x9b, 0xef, 0xab,
	0x7b, 0xec, 0xea, 0x2f, 0x10, 0xc0, 0xd4, 0x77, 0xc9, 0x9d, 0x17, 0xe9, 0x12, 0xba, 0x86, 0xd7,
	0xbe, 0x4b, 0x9c, 0xd5, 0x76, 0xb5, 0xc6, 0xf7, 0x38, 0xc2, 0x5e, 0xa8, 0xcb, 0x48, 0x87, 0x99,
	0xef, 0x92, 0xf0, 0xdb, 0x3a, 0x74, 0x02, 0xbc, 0xf6, 0x74, 0xa5, 0xb3, 0x84, 0x5e, 0xa4, 0x4f,
	0xac, 0xdf, 0x0a, 0x68, 0xc3, 0x3c, 0xd0, 0x47, 0x90, 0xf3, 0x94, 0xdf, 0x5f, 0x5d, 0xbe, 0x1f,
	0x5d, 0xf6, 0xef, 0x00, 0x03, 0x39, 0x4f, 0xd1, 0x2d, 0xa8, 0x42, 0x47, 0xf8, 0x53, 0xcb, 0xa6,
	0xb2, 0x50, 0x97, 0x37, 0xa3, 0xfe, 0x53, 0x32, 0x01, 0x24, 0xa7, 0x94, 0x30, 0x68, 0xac, 0x0f,
	0x56, 0x40, 0x14, 0x0e, 0xb1, 0x46, 0x21, 0x83, 0x0e, 0x04, 0x73, 0x36, 0xa8, 0x44, 0x02, 0x6f,
	0xba, 0x2e, 0x92, 0xce, 0x40, 0x52, 0x5a, 0xd3, 0x32, 0xa5, 0x65, 0x72, 0x30, 0x26, 0x1c, 0xfb,
	0xcc, 0xbb, 0x19, 0xd9, 0x60, 0xe2, 0x1e, 0x31, 0xc8, 0x81, 0xd9, 0x43, 0x59, 0xe5, 0xa4, 0xeb,
	0x88, 0x71, 0xc5, 0xb1, 0xe6, 0x85, 0x7c, 0x8f, 0x55, 0x0b, 0xd4, 0xd6, 0xd5, 0x77, 0x84, 0x43,
	0x8a, 0x13, 0x64, 0xfa, 0x5f, 0x88, 0x7f, 0x0e, 0x29, 0x7a, 0xc8, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x18, 0x71, 0x6f, 0x2e, 0x79, 0x03, 0x00, 0x00,
}
